In [160]:
import numpy as np

#Probelm 1

In [161]:
arr1 = np.random.randint(1,100,3)
arr2 = np.random.randint(1,100,6)
print(arr1)
print(arr2) 

[41 97 21]
[80  5  4 15 64 79]


In [162]:
def getSetsDiff(a, b):
    print("Arrays set difference: ", np.setxor1d(a, b))
    
getSetsDiff(arr1, arr2)   

Arrays set difference:  [ 4  5 15 21 41 64 79 80 97]


#Problem 2

In [163]:
arr3 = np.random.randint(10, 100, 10)
print(arr3)

[93 26 38 26 99 10 81 23 23 24]


In [164]:
oddNums = arr3[arr3%2==1]
print(oddNums)

[93 99 81 23 23]


#Problem 3

In [171]:
mixed_arr = ["s", 3, "dfd", 22, 10, "rrr", "e3", 1]

In [174]:
def writeCountInFile(arr):
    even_arr =[i for i in arr if type(i)==int and i%2==0]
    print(even_arr)
    odd_arr = [i for i in arr if type(i)==int and i%2==1]
    print(odd_arr)
    str_arr = [i for i in arr if type(i)==str]
    print(str_arr)
    
    all_lines = [
        "Number of strings: {}\n".format(len(str_arr)),
        "Number of odd integers: {}\n".format(len(odd_arr)),
        "Number of even integers: {}".format(len(even_arr)),
                ]
    
    file = open("b.txt", "w")
    file.writelines(all_lines)
    file.close()

In [175]:
writeCountInFile(mixed_arr)

[22, 10]
[3, 1]
['s', 'dfd', 'rrr', 'e3']
